// ═══════════════════════════════════════════════════════════════
//  BANCO DE PERGUNTAS — QUIZ IMOBILIÁRIO
//  200+ perguntas em 6 categorias
//  Cada pergunta: { category, question, options[], correct (index), explanation }
// ═══════════════════════════════════════════════════════════════

const ALL_QUESTIONS = [

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 1: DIREITO IMOBILIÁRIO (50 perguntas)             ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Direito Imobiliário",question:"No Direito Imobiliário brasileiro, qual é o ato que efetivamente transfere a propriedade de um imóvel?",options:["Assinatura do contrato de compra e venda","Registro do título no Cartório de Registro de Imóveis","Pagamento integral do preço","Escritura pública lavrada em cartório"],correct:1,explanation:"No Brasil, a propriedade imobiliária só se transfere com o registro do título aquisitivo no Cartório de Registro de Imóveis (art. 1.245 do Código Civil)."},
{category:"Direito Imobiliário",question:"O que é a matrícula do imóvel?",options:["O documento que comprova o pagamento do IPTU","O registro único e individualizado do imóvel no Cartório de Registro de Imóveis","A certidão negativa de ônus reais","O alvará de construção emitido pela prefeitura"],correct:1,explanation:"A matrícula é o registro individual do imóvel, onde consta todo seu histórico de proprietários, ônus e alterações (Lei 6.015/73)."},
{category:"Direito Imobiliário",question:"Qual é o prazo de usucapião extraordinária previsto no Código Civil?",options:["5 anos","10 anos","15 anos","20 anos"],correct:2,explanation:"A usucapião extraordinária exige posse contínua e incontestada por 15 anos, podendo ser reduzida para 10 anos se houver moradia ou obra (art. 1.238 CC)."},
{category:"Direito Imobiliário",question:"No contrato de locação regido pela Lei 8.245/91, qual é o prazo mínimo para o locador solicitar o imóvel na denúncia vazia?",options:["O contrato deve ter prazo igual ou superior a 30 meses","O contrato deve ter prazo de 12 meses","O contrato deve ter prazo de 24 meses","Não existe prazo mínimo para denúncia vazia"],correct:0,explanation:"A denúncia vazia (sem justificativa) só é possível em contratos com prazo igual ou superior a 30 meses, após o término do prazo (art. 46, Lei 8.245/91)."},
{category:"Direito Imobiliário",question:"De acordo com os dados sobre o mercado imobiliário brasileiro, qual é a situação da regularização de imóveis no país?",options:["70% a 80% dos imóveis estão regularizados","Apenas 25% dos imóveis possuem escritura pública","50% dos imóveis no Brasil são regularizados","A regularização atingiu 100% das capitais em 2025"],correct:2,explanation:"Estima-se que cerca de 50% dos imóveis no Brasil possuem algum tipo de irregularidade fundiária."},
{category:"Direito Imobiliário",question:"Qual é o impacto das ações judiciais por vícios construtivos nas disputas do mercado imobiliário?",options:["Representam cerca de 50% das disputas envolvendo construtoras","Correspondem a 70% a 80% das disputas judiciais","Estão em tendência de queda devido a novas regulamentações","Representam apenas 4% a 10% dos casos totais"],correct:1,explanation:"Os vícios construtivos representam a grande maioria (70-80%) das disputas judiciais envolvendo construtoras e incorporadoras."},

// -- Novas perguntas --
{category:"Direito Imobiliário",question:"Qual é o prazo de usucapião ordinária previsto no Código Civil?",options:["5 anos","10 anos","15 anos","20 anos"],correct:1,explanation:"A usucapião ordinária exige posse contínua por 10 anos, com justo título e boa-fé, podendo ser reduzida para 5 anos em situações específicas (art. 1.242 CC)."},
{category:"Direito Imobiliário",question:"O que é a evicção no Direito Imobiliário?",options:["O direito de preferência do inquilino","A perda do imóvel por decisão judicial em favor de terceiro com direito anterior","O registro da escritura pública","A retomada do imóvel pelo locador"],correct:1,explanation:"Evicção ocorre quando o comprador perde o imóvel por sentença judicial que reconhece direito anterior de terceiro (arts. 447 a 457 CC)."},
{category:"Direito Imobiliário",question:"Qual é o prazo prescricional para cobrar vícios construtivos aparentes após a entrega do imóvel?",options:["30 dias","90 dias","1 ano","5 anos"],correct:1,explanation:"O prazo para reclamar vícios aparentes é de 90 dias para bens duráveis, conforme o Código de Defesa do Consumidor (art. 26, II)."},
{category:"Direito Imobiliário",question:"O que é a cláusula de inalienabilidade em um imóvel?",options:["Proibição de alugar o imóvel","Restrição que impede a venda do imóvel por determinado período","Obrigação de reformar o imóvel","Isenção de IPTU"],correct:1,explanation:"A cláusula de inalienabilidade impede a transferência do bem, podendo ser imposta em doações ou testamentos (art. 1.911 CC)."},
{category:"Direito Imobiliário",question:"O que é o direito de superfície?",options:["O direito de usar o subsolo do terreno","O direito de construir ou plantar em terreno alheio","O direito de passagem pelo terreno vizinho","O direito de preferência na compra"],correct:1,explanation:"O direito de superfície permite construir ou plantar em terreno de outrem, por prazo determinado ou indeterminado (arts. 1.369 a 1.377 CC)."},
{category:"Direito Imobiliário",question:"Qual é a garantia legal de solidez e segurança da construção prevista no Código Civil?",options:["1 ano","3 anos","5 anos","10 anos"],correct:2,explanation:"O construtor responde por 5 anos pela solidez e segurança do trabalho de engenharia e dos materiais empregados (art. 618 CC)."},
{category:"Direito Imobiliário",question:"O que é o patrimônio de afetação na incorporação imobiliária?",options:["Penhora dos bens do incorporador","Separação do patrimônio do empreendimento do patrimônio geral do incorporador","Bloqueio judicial de contas bancárias","Hipoteca do terreno"],correct:1,explanation:"O patrimônio de afetação separa os recursos do empreendimento dos demais bens do incorporador, protegendo os compradores (Lei 4.591/64, art. 31-A)."},
{category:"Direito Imobiliário",question:"O que é a escritura pública de compra e venda de imóvel?",options:["O contrato particular entre as partes","O documento lavrado em Tabelionato de Notas que formaliza a transação","O registro no Cartório de Registro de Imóveis","O laudo de avaliação do imóvel"],correct:1,explanation:"A escritura pública é o instrumento lavrado pelo Tabelião de Notas, obrigatório para imóveis acima de 30 salários mínimos (art. 108 CC)."},
{category:"Direito Imobiliário",question:"Para imóveis de qual valor a escritura pública é dispensável, podendo usar instrumento particular?",options:["Acima de 50 salários mínimos","Acima de 100 salários mínimos","Até 30 salários mínimos","Até 10 salários mínimos"],correct:2,explanation:"Para negócios cujo valor não ultrapasse 30 salários mínimos, a lei dispensa a escritura pública (art. 108 CC)."},
{category:"Direito Imobiliário",question:"O que é o direito de preferência (preempção) do inquilino?",options:["O direito de renovar o contrato automaticamente","O direito de ser o primeiro a comprar o imóvel em caso de venda, em igualdade de condições","O direito de sublocar o imóvel","O direito de reduzir o valor do aluguel"],correct:1,explanation:"O inquilino tem preferência para adquirir o imóvel locado em igualdade de condições com terceiros (art. 27, Lei 8.245/91)."},
{category:"Direito Imobiliário",question:"O que é o compromisso de compra e venda irretratável?",options:["Um contrato que pode ser desfeito a qualquer momento","Um contrato preliminar que obriga as partes a celebrar o contrato definitivo","Uma escritura pública de doação","Um contrato de locação de longo prazo"],correct:1,explanation:"O compromisso irretratável é um contrato preliminar que, registrado, confere direito real ao compromissário comprador (art. 1.417 CC)."},
{category:"Direito Imobiliário",question:"Qual é a principal lei que regulamenta os condomínios edilícios no Brasil?",options:["Código Civil (arts. 1.331 a 1.358)","Lei 4.591/64 apenas","Código de Processo Civil","Lei 8.245/91"],correct:0,explanation:"O Código Civil de 2002 passou a regulamentar os condomínios edilícios nos arts. 1.331 a 1.358, sendo complementado pela Lei 4.591/64."},
{category:"Direito Imobiliário",question:"O que são as arras confirmatórias no contrato imobiliário?",options:["Um tipo de garantia hipotecária","Sinal dado como confirmação do negócio e início de pagamento","Multa por rescisão contratual","Taxa de corretagem"],correct:1,explanation:"Arras confirmatórias funcionam como sinal e princípio de pagamento, confirmando a vontade das partes (art. 418 CC)."},
{category:"Direito Imobiliário",question:"O que é a ação de adjudicação compulsória?",options:["Ação para despejar inquilino","Ação para obter registro do imóvel quando o vendedor se recusa a outorgar escritura","Ação de cobrança de condomínio","Ação de usucapião"],correct:1,explanation:"A adjudicação compulsória permite ao comprador obter judicialmente a transferência do imóvel quando o vendedor descumpre a obrigação."},
{category:"Direito Imobiliário",question:"Qual é o conceito de bem de família legal?",options:["Imóvel rural de até 4 módulos fiscais","O imóvel residencial próprio do casal ou entidade familiar, impenhorável por dívidas","Imóvel doado em testamento","Imóvel registrado em nome de menor"],correct:1,explanation:"O bem de família legal é o imóvel residencial próprio, protegido contra penhora por dívidas (Lei 8.009/90)."},
{category:"Direito Imobiliário",question:"Em qual situação o bem de família pode ser penhorado?",options:["Dívida de cartão de crédito","Financiamento do próprio imóvel","Dívida trabalhista de empregado doméstico apenas","Todas as dívidas acima de 100 salários mínimos"],correct:1,explanation:"O bem de família pode ser penhorado por dívida de financiamento para aquisição do próprio imóvel, entre outras exceções legais (art. 3º, Lei 8.009/90)."},
{category:"Direito Imobiliário",question:"O que é a retificação de registro imobiliário?",options:["A mudança de endereço do cartório","A correção de dados incorretos na matrícula do imóvel","A transferência de propriedade","A averbação de construção"],correct:1,explanation:"A retificação corrige erros ou omissões no registro imobiliário, podendo ser administrativa ou judicial (art. 213, Lei 6.015/73)."},
{category:"Direito Imobiliário",question:"O que é o memorial de incorporação?",options:["A planta baixa do imóvel","O conjunto de documentos que o incorporador deve registrar antes de vender unidades na planta","O contrato de construção","O laudo de avaliação do terreno"],correct:1,explanation:"O memorial de incorporação é o conjunto de documentos registrados no CRI antes de iniciar a venda de unidades autônomas (art. 32, Lei 4.591/64)."},
{category:"Direito Imobiliário",question:"O que é servidão de passagem?",options:["Obrigação de construir muro divisório","Direito real sobre imóvel alheio que impõe ao prédio serviente um ônus em benefício do prédio dominante","Direito de construir em terreno vizinho","Obrigação de plantar árvores na divisa"],correct:1,explanation:"A servidão é um direito real que onera um prédio (serviente) em favor de outro (dominante), como passagem de pessoas ou tubulações (arts. 1.378 a 1.389 CC)."},
{category:"Direito Imobiliário",question:"Qual é o prazo decadencial para o condomínio cobrar cotas condominiais em atraso?",options:["2 anos","5 anos","10 anos","Não há prazo decadencial, há prazo prescricional de 5 anos"],correct:3,explanation:"A cobrança de cotas condominiais tem prazo prescricional de 5 anos (art. 206, §5º, I, CC), não decadencial."},
{category:"Direito Imobiliário",question:"O que é a averbação no registro de imóveis?",options:["O primeiro registro de propriedade","A anotação de alterações ocorridas no imóvel ou nos titulares de direitos","A emissão da matrícula do imóvel","O cancelamento do registro"],correct:1,explanation:"Averbação é a anotação de fatos que alteram o registro, como construção, casamento, penhora, entre outros (art. 167, II, Lei 6.015/73)."},
{category:"Direito Imobiliário",question:"O que é a cláusula de reversão em doação de imóvel?",options:["O donatário devolve o imóvel ao doar para terceiro","Se o donatário falecer antes do doador, o bem retorna ao doador","O doador pode revogar a doação a qualquer momento","O imóvel é automaticamente vendido após 10 anos"],correct:1,explanation:"A cláusula de reversão determina que, se o donatário falecer antes do doador, o bem retorna ao patrimônio do doador (art. 547 CC)."},
{category:"Direito Imobiliário",question:"Qual é a multa máxima por atraso no pagamento de condomínio prevista no Código Civil?",options:["5%","10%","2%","20%"],correct:2,explanation:"A multa moratória para cotas condominiais não pode exceder 2% sobre o débito (art. 1.336, §1º, CC)."},
{category:"Direito Imobiliário",question:"O que é a usucapião especial urbana (constitucional)?",options:["Posse de 15 anos em imóvel urbano","Posse de 5 anos em área urbana de até 250m², sem ser proprietário de outro imóvel","Posse de 10 anos em imóvel comercial","Posse de 2 anos em imóvel abandonado"],correct:1,explanation:"A usucapião especial urbana exige posse de 5 anos em área de até 250m², para moradia, sem outro imóvel (art. 183, CF e art. 1.240 CC)."},
{category:"Direito Imobiliário",question:"O que é o distrato de incorporação imobiliária conforme a Lei 13.786/2018?",options:["A rescisão contratual com restituição integral imediata","A resolução do contrato com retenção de até 50% dos valores pagos pela incorporadora","A anulação judicial do contrato","A transferência do contrato a terceiro"],correct:1,explanation:"A Lei do Distrato permite retenção de até 50% (com patrimônio de afetação) ou 25% (sem) dos valores pagos pelo adquirente que desistir."},
{category:"Direito Imobiliário",question:"O que é o direito real de laje?",options:["O direito de usar a laje para antena de celular","O direito de construir sobre ou sob construção alheia, como unidade autônoma","O direito de impermeabilizar a laje do vizinho","O direito de acessar o telhado do condomínio"],correct:1,explanation:"O direito real de laje permite ao titular manter unidade distinta da construção-base, com matrícula própria (art. 1.510-A CC)."},
{category:"Direito Imobiliário",question:"O que é a hipoteca?",options:["A venda forçada do imóvel","Direito real de garantia que grava o imóvel sem transferir a posse ao credor","A transferência definitiva da propriedade ao banco","O aluguel do imóvel ao credor"],correct:1,explanation:"A hipoteca é direito real de garantia sobre imóvel, sem transferência de posse ou propriedade ao credor (arts. 1.473 a 1.505 CC)."},
{category:"Direito Imobiliário",question:"Qual a diferença entre hipoteca e alienação fiduciária de imóvel?",options:["Não há diferença prática","Na alienação fiduciária, a propriedade é transferida ao credor até a quitação; na hipoteca, o imóvel permanece com o devedor","Na hipoteca, o imóvel fica com o banco; na alienação fiduciária, com o devedor","A hipoteca é mais rápida na execução"],correct:1,explanation:"Na alienação fiduciária, o credor detém a propriedade resolúvel até a quitação. Na hipoteca, o devedor mantém a propriedade plena, com ônus registrado."},
{category:"Direito Imobiliário",question:"Qual é a função da certidão de ônus reais?",options:["Comprovar o pagamento de IPTU","Informar se existem gravames, penhoras ou ônus sobre o imóvel","Confirmar a metragem do terreno","Autorizar a construção no terreno"],correct:1,explanation:"A certidão de ônus reais revela se há hipotecas, penhoras, arrestos ou outros gravames registrados na matrícula do imóvel."},
{category:"Direito Imobiliário",question:"O que é a multipropriedade imobiliária (time-sharing)?",options:["Propriedade de múltiplos imóveis por uma pessoa","Regime em que cada titular tem o direito de uso exclusivo do imóvel por período determinado do ano","Condomínio com mais de 100 unidades","Propriedade compartilhada entre cônjuges"],correct:1,explanation:"A multipropriedade é o regime de condomínio em que cada titular usa o imóvel por fração temporal definida (arts. 1.358-B a 1.358-U CC, Lei 13.777/2018)."},
{category:"Direito Imobiliário",question:"Qual é o prazo máximo de vigência do contrato de locação não residencial para fins de renovatória?",options:["5 anos","10 anos","Não há limite","30 anos"],correct:0,explanation:"O contrato deve ter prazo mínimo de 5 anos (somados os prazos ininterruptos) para a ação renovatória de locação comercial (art. 51, Lei 8.245/91)."},
{category:"Direito Imobiliário",question:"Em caso de venda do imóvel locado, o que acontece com o contrato de locação?",options:["O contrato é automaticamente rescindido","O novo proprietário deve respeitar o contrato se houver cláusula de vigência averbada na matrícula","O inquilino deve sair imediatamente","O contrato é renovado automaticamente por mais 30 meses"],correct:1,explanation:"A cláusula de vigência averbada na matrícula obriga o adquirente a respeitar a locação durante o prazo contratual (art. 8º, Lei 8.245/91)."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 2: DIREITO TRABALHISTA (35 perguntas)              ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Direito Trabalhista",question:"O corretor de imóveis que trabalha com autonomia, sem subordinação, habitualidade ou exclusividade, possui vínculo empregatício com a imobiliária?",options:["Sim, sempre","Não, pois falta o requisito da subordinação jurídica","Sim, se receber comissão","Depende exclusivamente do valor da comissão"],correct:1,explanation:"Sem os requisitos da relação de emprego (subordinação, pessoalidade, habitualidade e onerosidade), não há vínculo empregatício (art. 3º CLT)."},
{category:"Direito Trabalhista",question:"Qual é o principal risco trabalhista para imobiliárias que contratam corretores como autônomos?",options:["Pagamento de IPTU em atraso","Reconhecimento de vínculo empregatício na Justiça do Trabalho","Multa do CRECI","Perda do alvará de funcionamento"],correct:1,explanation:"O principal risco é a Justiça do Trabalho reconhecer o vínculo empregatício se presentes os requisitos da relação de emprego."},
{category:"Direito Trabalhista",question:"Qual situação pode levar ao reconhecimento de vínculo empregatício entre uma imobiliária e um corretor?",options:["O corretor receber apenas comissões pelas vendas","O corretor possuir inscrição regular no CRECI","Estarem presentes subordinação, pessoalidade, habitualidade e onerosidade","O corretor utilizar veículo próprio para visitar imóveis"],correct:2,explanation:"O vínculo é reconhecido quando presentes todos os requisitos legais: subordinação, pessoalidade, habitualidade e onerosidade (art. 3º CLT)."},
{category:"Direito Trabalhista",question:"Sobre a jornada de trabalho do corretor de imóveis, é correto afirmar que:",options:["Todo corretor possui jornada fixa de 8 horas diárias","O corretor autônomo faz jus ao pagamento de horas extras","O simples cumprimento de metas caracteriza vínculo empregatício","O corretor autônomo organiza sua própria rotina; o empregado segue regras trabalhistas"],correct:3,explanation:"O corretor autônomo tem liberdade de horário. Já o corretor empregado está sujeito às regras da CLT sobre jornada de trabalho."},

// -- Novas perguntas --
{category:"Direito Trabalhista",question:"Quais são os 4 requisitos cumulativos para caracterizar a relação de emprego?",options:["Contrato, CTPS, salário e férias","Subordinação, pessoalidade, habitualidade e onerosidade","Registro no CRECI, comissão, horário e exclusividade","Contrato escrito, local fixo, horário e benefícios"],correct:1,explanation:"Os requisitos são: subordinação (ordens), pessoalidade (insubstituível), habitualidade (não eventual) e onerosidade (remuneração) — art. 3º CLT."},
{category:"Direito Trabalhista",question:"O que é a subordinação jurídica no contexto trabalhista?",options:["O trabalhador depender financeiramente do empregador","O trabalhador estar sujeito ao poder de direção e comando do empregador","O trabalhador trabalhar exclusivamente para uma empresa","O trabalhador usar uniforme da empresa"],correct:1,explanation:"Subordinação jurídica é a sujeição do empregado ao poder diretivo do empregador, que organiza, controla e disciplina a prestação de serviço."},
{category:"Direito Trabalhista",question:"A Reforma Trabalhista (Lei 13.467/2017) trouxe qual novidade sobre o trabalho autônomo?",options:["Proibiu a contratação de autônomos","Permitiu a contratação com exclusividade e continuidade sem configurar vínculo, desde que cumpridas formalidades","Obrigou registro em CTPS de todos os autônomos","Reduziu a comissão máxima para 3%"],correct:1,explanation:"O art. 442-B da CLT (incluído pela Reforma) prevê que a contratação de autônomo, mesmo com exclusividade e continuidade, não gera vínculo, observadas as condições legais."},
{category:"Direito Trabalhista",question:"Qual é o prazo prescricional para o trabalhador ajuizar reclamação trabalhista após a extinção do contrato?",options:["1 ano","2 anos","5 anos","10 anos"],correct:1,explanation:"O prazo prescricional é de 2 anos após a extinção do contrato, podendo reclamar os últimos 5 anos de direitos (art. 7º, XXIX, CF)."},
{category:"Direito Trabalhista",question:"O que é o aviso prévio proporcional ao tempo de serviço?",options:["Aviso de 30 dias fixos para todos","30 dias + 3 dias por ano trabalhado, até 90 dias no total","15 dias por ano trabalhado","60 dias fixos após 5 anos"],correct:1,explanation:"O aviso prévio é de 30 dias, acrescido de 3 dias por ano de serviço, limitado a 90 dias no total (Lei 12.506/2011)."},
{category:"Direito Trabalhista",question:"O corretor de imóveis empregado tem direito a comissão sobre vendas realizadas durante o aviso prévio?",options:["Não, o aviso prévio exclui comissões","Sim, durante o aviso prévio todos os direitos são mantidos","Apenas se houver acordo expresso","Somente se o aviso for indenizado"],correct:1,explanation:"Durante o aviso prévio, o contrato de trabalho permanece em vigor, mantendo todos os direitos e obrigações, inclusive comissões."},
{category:"Direito Trabalhista",question:"O que é a justa causa para demissão do empregado no mercado imobiliário?",options:["Qualquer insatisfação do empregador","Falta grave prevista no art. 482 da CLT, como improbidade ou desídia","Vendas abaixo da meta por 2 meses","Recusa em trabalhar aos domingos"],correct:1,explanation:"A justa causa exige falta grave tipificada no art. 482 da CLT, como ato de improbidade, incontinência, desídia, entre outras."},
{category:"Direito Trabalhista",question:"O que é o contrato de trabalho intermitente, aplicável ao mercado imobiliário?",options:["Contrato sem prazo definido","Contrato com alternância de períodos de prestação de serviço e inatividade","Contrato de experiência de 90 dias","Contrato apenas para finais de semana"],correct:1,explanation:"O contrato intermitente (art. 443, §3º, CLT) prevê alternância entre períodos de trabalho e inatividade, com convocação prévia."},
{category:"Direito Trabalhista",question:"O vale-transporte é obrigatório para o corretor de imóveis empregado?",options:["Não, nunca","Sim, quando solicitado pelo empregado para deslocamento residência-trabalho","Apenas para quem mora a mais de 10 km","Somente se o salário for inferior a 3 salários mínimos"],correct:1,explanation:"O vale-transporte é devido ao empregado que o solicitar para deslocamento casa-trabalho-casa (Lei 7.418/85)."},
{category:"Direito Trabalhista",question:"O FGTS é depositado para o corretor de imóveis contratado como autônomo?",options:["Sim, o FGTS é obrigatório para todos","Não, o FGTS é direito exclusivo de empregados com vínculo","Sim, mas com alíquota reduzida de 4%","Depende do faturamento da imobiliária"],correct:1,explanation:"O FGTS (8% sobre a remuneração) é obrigação do empregador apenas para empregados com vínculo formal (Lei 8.036/90)."},
{category:"Direito Trabalhista",question:"O que é a responsabilidade solidária trabalhista entre empresas do mesmo grupo econômico?",options:["Cada empresa responde apenas por seus empregados","Todas as empresas do grupo podem ser responsabilizadas pelas dívidas trabalhistas de qualquer uma delas","Apenas a empresa matriz responde","A responsabilidade é limitada ao capital social"],correct:1,explanation:"Empresas do mesmo grupo econômico são solidariamente responsáveis pelas obrigações trabalhistas (art. 2º, §2º, CLT)."},
{category:"Direito Trabalhista",question:"O corretor de imóveis empregado pode ter seu salário composto exclusivamente por comissões?",options:["Não, deve receber salário fixo obrigatoriamente","Sim, é possível o comissionista puro, garantido o salário mínimo","Somente se houver acordo coletivo","Apenas nos primeiros 6 meses de contrato"],correct:1,explanation:"É válido o comissionista puro (só comissões), mas deve ser garantido ao menos o salário mínimo mensal (art. 7º, VII, CF e Súmula 340 TST)."},
{category:"Direito Trabalhista",question:"O que é o contrato de experiência e qual seu prazo máximo?",options:["Contrato temporário de até 120 dias","Contrato de avaliação de até 90 dias, prorrogável uma vez","Contrato de 6 meses para todos os cargos","Contrato verbal de até 30 dias"],correct:1,explanation:"O contrato de experiência pode durar até 90 dias, admitida uma única prorrogação dentro desse limite (art. 445, parágrafo único, CLT)."},
{category:"Direito Trabalhista",question:"A imobiliária pode descontar do corretor empregado valores de vendas que foram distratadas pelo cliente?",options:["Sim, sempre","Não, salvo se comprovada culpa do corretor e houver previsão contratual","Sim, até 50% do valor da comissão","Apenas se o cliente estiver inadimplente há mais de 90 dias"],correct:1,explanation:"Descontos salariais só são permitidos com previsão legal ou contratual e quando houver culpa do empregado (art. 462 CLT)."},
{category:"Direito Trabalhista",question:"O que é o assédio moral no ambiente imobiliário e qual sua consequência jurídica?",options:["Apenas ofensas verbais, sem consequência","Conduta abusiva e repetitiva que humilha o trabalhador, podendo gerar rescisão indireta e indenização","Divergência de opiniões entre colegas","Cobrança normal de metas"],correct:1,explanation:"Assédio moral é conduta abusiva, repetitiva, que degrada o ambiente de trabalho, podendo gerar rescisão indireta (art. 483 CLT) e dano moral."},
{category:"Direito Trabalhista",question:"O que é a rescisão indireta do contrato de trabalho?",options:["Demissão sem justa causa","Pedido de demissão do empregado","Quando o empregado 'demite' o empregador por falta grave deste","Acordo entre as partes para encerrar o contrato"],correct:2,explanation:"A rescisão indireta ocorre quando o empregador comete falta grave (art. 483 CLT), garantindo ao empregado os mesmos direitos da demissão sem justa causa."},
{category:"Direito Trabalhista",question:"O que é o acordo para rescisão do contrato de trabalho previsto na Reforma Trabalhista?",options:["Acordo verbal sem formalização","Rescisão por acordo com aviso prévio e multa do FGTS pela metade e saque de 80% do FGTS","Demissão em massa autorizada pelo sindicato","Transferência para outra filial"],correct:1,explanation:"O acordo de rescisão (art. 484-A CLT) prevê metade do aviso prévio indenizado e da multa do FGTS (20%), com saque de 80% do saldo."},
{category:"Direito Trabalhista",question:"O recepcionista de uma imobiliária que trabalha 6 horas por dia tem direito a intervalo intrajornada de quanto tempo?",options:["Não tem direito a intervalo","15 minutos","30 minutos","1 hora"],correct:1,explanation:"Para jornadas entre 4 e 6 horas, o intervalo intrajornada é de 15 minutos (art. 71, §1º, CLT)."},
{category:"Direito Trabalhista",question:"A imobiliária pode exigir exclusividade do corretor autônomo?",options:["Não, exclusividade configura vínculo automaticamente","Sim, desde que previsto em contrato, após a Reforma Trabalhista","Apenas com autorização do CRECI","Somente por acordo coletivo"],correct:1,explanation:"Após a Reforma Trabalhista (art. 442-B CLT), a exclusividade e continuidade na prestação de serviço autônomo não caracterizam, por si só, vínculo."},
{category:"Direito Trabalhista",question:"Qual é a consequência de não registrar o empregado em CTPS?",options:["Apenas uma advertência verbal","Multa de R$ 3.000,00 por empregado não registrado (R$ 800,00 para ME/EPP)","Suspensão da atividade por 30 dias","Nenhuma, se houver contrato verbal"],correct:1,explanation:"A falta de registro gera multa de R$ 3.000,00 por empregado (R$ 800,00 para microempresas), conforme art. 47 da CLT."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 3: DIREITO PREVIDENCIÁRIO (30 perguntas)           ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Direito Previdenciário",question:"Na construção civil, quem é o responsável pelo recolhimento das contribuições previdenciárias dos trabalhadores da obra?",options:["O comprador do imóvel","O corretor responsável pela venda","O dono da obra ou o construtor/empreiteiro","O cartório de registro de imóveis"],correct:2,explanation:"O dono da obra ou o construtor/empreiteiro é responsável pelo recolhimento das contribuições previdenciárias (art. 30, VI, Lei 8.212/91)."},
{category:"Direito Previdenciário",question:"O corretor de imóveis autônomo é considerado, para fins previdenciários, como:",options:["Segurado empregado","Segurado facultativo","Contribuinte individual","Segurado especial"],correct:2,explanation:"O corretor autônomo é enquadrado como contribuinte individual do INSS (art. 11, V, 'h', Lei 8.213/91)."},
{category:"Direito Previdenciário",question:"O que é a CND (Certidão Negativa de Débitos) do INSS exigida na averbação de construção?",options:["Documento que comprova a inexistência de débitos previdenciários relativos à obra","Certidão de nascimento do proprietário","Documento que comprova o pagamento do IPTU","Licença ambiental para construção"],correct:0,explanation:"A CND comprova a quitação das contribuições previdenciárias da obra, exigida para averbar a construção no Registro de Imóveis."},
{category:"Direito Previdenciário",question:"Qual é a alíquota de contribuição previdenciária do contribuinte individual (corretor autônomo) sobre o salário de contribuição?",options:["8%","11%","20%","27,5%"],correct:2,explanation:"O contribuinte individual contribui com 20% sobre o salário de contribuição (art. 21, Lei 8.212/91). A alíquota de 11% é para o plano simplificado."},
{category:"Direito Previdenciário",question:"Como funciona a aposentadoria do corretor de imóveis autônomo?",options:["Possui aposentadoria especial apenas por exercer a profissão","Pode se aposentar com 25 anos de atividade, sem contribuições","Deve contribuir como contribuinte individual e cumprir os requisitos legais vigentes","O registro no CRECI substitui as contribuições ao INSS"],correct:2,explanation:"O corretor autônomo deve contribuir como contribuinte individual ao INSS e cumprir os requisitos de aposentadoria vigentes."},

// -- Novas perguntas --
{category:"Direito Previdenciário",question:"Qual é o teto do salário de contribuição do INSS em 2026?",options:["R$ 6.433,57","R$ 7.786,02","R$ 8.157,41","R$ 10.000,00"],correct:2,explanation:"O teto do INSS é reajustado anualmente. O contribuinte individual não pode contribuir sobre base superior ao teto."},
{category:"Direito Previdenciário",question:"O que é o plano simplificado de previdência para o contribuinte individual?",options:["Contribuição de 20% sobre qualquer valor","Contribuição de 11% sobre o salário mínimo, com direito apenas à aposentadoria por idade","Isenção total de contribuição","Contribuição de 5% sobre o teto do INSS"],correct:1,explanation:"O plano simplificado permite contribuir com 11% sobre o salário mínimo, mas limita a aposentadoria por idade no valor de 1 salário mínimo."},
{category:"Direito Previdenciário",question:"O que é a matrícula CEI/CNO de uma obra de construção civil?",options:["O CNPJ da construtora","O cadastro da obra junto à Receita Federal para fins previdenciários","O registro da obra no CREA","A licença de construção da prefeitura"],correct:1,explanation:"O CNO (Cadastro Nacional de Obras) substitui o antigo CEI e vincula a obra à Receita Federal para controle das contribuições previdenciárias."},
{category:"Direito Previdenciário",question:"O que acontece se o corretor autônomo ficar mais de 12 meses sem contribuir ao INSS?",options:["Nada, a qualidade de segurado é vitalícia","Perde a qualidade de segurado e a cobertura previdenciária","Continua coberto por mais 5 anos","Recebe restituição dos valores pagos"],correct:1,explanation:"O contribuinte individual mantém qualidade de segurado por até 12 meses após cessar as contribuições (período de graça — art. 15, Lei 8.213/91)."},
{category:"Direito Previdenciário",question:"O corretor autônomo tem direito a auxílio-doença do INSS?",options:["Não, apenas empregados CLT","Sim, desde que tenha contribuído por no mínimo 12 meses (carência) e esteja em dia","Sim, sem necessidade de carência","Apenas com seguro privado"],correct:1,explanation:"O auxílio por incapacidade temporária exige carência de 12 contribuições mensais e qualidade de segurado (art. 25, I, Lei 8.213/91)."},
{category:"Direito Previdenciário",question:"O que é o fator previdenciário e como impacta a aposentadoria do corretor?",options:["Um bônus fixo de 20% sobre o benefício","Uma fórmula que considera idade, tempo de contribuição e expectativa de vida no cálculo do benefício","Um desconto obrigatório de 10%","O valor do INSS pago mensalmente"],correct:1,explanation:"O fator previdenciário é uma fórmula que pode reduzir ou aumentar o benefício, levando em conta idade, tempo de contribuição e expectativa de vida."},
{category:"Direito Previdenciário",question:"A contribuição previdenciária sobre a folha de pagamento da imobiliária é de qual percentual (cota patronal)?",options:["8%","11%","20%","27,5%"],correct:2,explanation:"A contribuição patronal sobre a folha de salários é de 20% (art. 22, I, Lei 8.212/91), além do RAT e contribuições a terceiros."},
{category:"Direito Previdenciário",question:"O que é a desoneração da folha de pagamento e qual setor do mercado imobiliário se beneficiou?",options:["Isenção total de INSS para todas as empresas","Substituição da contribuição patronal sobre a folha por contribuição sobre a receita bruta, beneficiando a construção civil","Redução do FGTS para 4%","Eliminação do 13º salário"],correct:1,explanation:"A desoneração substitui os 20% patronais sobre a folha por percentual sobre a receita bruta, beneficiando setores como construção civil."},
{category:"Direito Previdenciário",question:"O MEI (Microempreendedor Individual) pode atuar como corretor de imóveis?",options:["Sim, com registro no CRECI","Não, a atividade de corretor de imóveis não é permitida como MEI","Sim, sem necessidade de CRECI","Apenas em cidades com menos de 100 mil habitantes"],correct:1,explanation:"A atividade de corretor de imóveis não consta na lista de ocupações permitidas para MEI, pois exige registro no CRECI."},
{category:"Direito Previdenciário",question:"Qual é a regra de transição da aposentadoria por idade após a Reforma da Previdência (EC 103/2019)?",options:["65 anos para homens e mulheres","65 anos para homens e 62 anos para mulheres, com 15/20 anos de contribuição","60 anos para ambos os sexos","70 anos para todos"],correct:1,explanation:"A Reforma fixou 65 anos (homens) e 62 anos (mulheres), com tempo mínimo de contribuição de 20 anos (homens) e 15 anos (mulheres)."},
{category:"Direito Previdenciário",question:"O que é o salário de contribuição do INSS?",options:["O salário mínimo nacional","A base de cálculo sobre a qual incide a contribuição previdenciária","O valor do benefício recebido","O total de descontos na folha de pagamento"],correct:1,explanation:"Salário de contribuição é a base de cálculo da contribuição previdenciária, limitada ao teto do INSS (art. 28, Lei 8.212/91)."},
{category:"Direito Previdenciário",question:"O corretor de imóveis empregado tem a contribuição previdenciária retida pela imobiliária. Quais são as alíquotas progressivas?",options:["8%, 9% e 11%","7,5%, 9%, 12% e 14%","5%, 10% e 15%","20% fixo"],correct:1,explanation:"Após a Reforma (EC 103/2019), as alíquotas são progressivas: 7,5%, 9%, 12% e 14%, aplicadas por faixa de remuneração."},
{category:"Direito Previdenciário",question:"O que é o PPRA/PGR e qual sua relação com o mercado imobiliário?",options:["Plano de Previdência para Autônomos","Programa de Gerenciamento de Riscos, obrigatório para empresas da construção civil","Plano de Pagamento de Receitas Acessórias","Programa de Promoção de Regularização de Áreas"],correct:1,explanation:"O PGR (antigo PPRA) é obrigatório para identificar e controlar riscos ambientais no ambiente de trabalho, especialmente na construção civil."},
{category:"Direito Previdenciário",question:"O que é a aposentadoria especial e ela se aplica a corretores de imóveis?",options:["Aposentadoria aos 50 anos para qualquer profissão","Aposentadoria para quem trabalha exposto a agentes nocivos — não se aplica a corretores","Aposentadoria antecipada para mulheres corretoras","Aposentadoria por invalidez para acidentes de trabalho"],correct:1,explanation:"A aposentadoria especial é para trabalhadores expostos a agentes nocivos (15, 20 ou 25 anos). Não se aplica à atividade de corretagem imobiliária."},
{category:"Direito Previdenciário",question:"Qual documento comprova o tempo de contribuição do corretor autônomo ao INSS?",options:["Carteira do CRECI","Guias de recolhimento (GPS/DARF) e CNIS","Declaração do imposto de renda","Contrato de prestação de serviços"],correct:1,explanation:"O tempo de contribuição é comprovado pelas guias de pagamento e pelo CNIS (Cadastro Nacional de Informações Sociais)."},
{category:"Direito Previdenciário",question:"O que é o RAT (Riscos Ambientais do Trabalho) e como impacta construtoras e imobiliárias?",options:["Imposto sobre renda de aluguéis","Contribuição adicional ao INSS baseada no grau de risco da atividade da empresa","Relatório Anual de Tributação","Registro de Acidentes de Trânsito"],correct:1,explanation:"O RAT é uma contribuição patronal adicional (1%, 2% ou 3%) ao INSS, baseada no grau de risco da atividade — construção civil tem alíquota maior."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 4: DIREITO SOCIETÁRIO (35 perguntas)               ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Direito Societário",question:"Qual tipo societário é o mais utilizado no Brasil e exige capital social dividido em quotas?",options:["Sociedade Anônima (S.A.)","Sociedade Limitada (Ltda.)","Sociedade em Comandita Simples","Sociedade em Nome Coletivo"],correct:1,explanation:"A Sociedade Limitada é o tipo mais comum no Brasil, com capital dividido em quotas e responsabilidade limitada dos sócios."},
{category:"Direito Societário",question:"Qual é o órgão responsável pelo registro de uma Sociedade Limitada?",options:["Cartório de Registro de Títulos e Documentos","Junta Comercial do Estado","Cartório de Registro de Imóveis","Receita Federal do Brasil"],correct:1,explanation:"As sociedades empresárias, incluindo a Ltda., são registradas na Junta Comercial (art. 1.150 CC e Lei 8.934/94)."},
{category:"Direito Societário",question:"Na Sociedade Limitada, a responsabilidade dos sócios é limitada a quê?",options:["Ao valor de suas quotas apenas","Ao total do capital social, solidariamente, até sua integralização","Ao patrimônio pessoal de cada sócio","Ao dobro do valor investido"],correct:1,explanation:"Os sócios respondem solidariamente pela integralização do capital social. Após integralizado, a responsabilidade é limitada ao valor das quotas (art. 1.052 CC)."},
{category:"Direito Societário",question:"O que é a desconsideração da personalidade jurídica prevista no art. 50 do Código Civil?",options:["A extinção da empresa por decisão judicial","A suspensão temporária do CNPJ","A responsabilização dos sócios por obrigações da empresa em caso de abuso","A mudança do tipo societário por determinação do juiz"],correct:2,explanation:"A desconsideração permite alcançar o patrimônio pessoal dos sócios quando há abuso da personalidade jurídica, desvio de finalidade ou confusão patrimonial."},
{category:"Direito Societário",question:"Qual é a principal finalidade de uma holding patrimonial no contexto imobiliário?",options:["Administrar folha de pagamento dos funcionários","Concentrar a titularidade de bens imóveis para planejamento sucessório e tributário","Emitir ações na Bolsa de Valores","Obter financiamento junto ao BNDES"],correct:1,explanation:"A holding patrimonial concentra imóveis em pessoa jurídica, facilitando o planejamento sucessório, tributário e a proteção patrimonial."},
{category:"Direito Societário",question:"Qual vantagem tributária uma holding patrimonial pode oferecer na locação de imóveis em relação à pessoa física?",options:["Isenção total de tributos","Alíquota efetiva de tributos sobre receita de aluguel pode ser menor pelo Lucro Presumido","Não incide nenhum imposto sobre aluguel recebido por holding","O IPTU é isento para holdings"],correct:1,explanation:"No Lucro Presumido, a alíquota efetiva sobre aluguéis pode ser em torno de 11-14%, enquanto pessoa física pode pagar até 27,5% de IRPF."},
{category:"Direito Societário",question:"Qual tipo societário é mais comum para constituição de uma holding familiar?",options:["Sociedade Anônima de capital aberto","Empresa Individual de Responsabilidade Limitada (EIRELI)","Sociedade Limitada (Ltda.)","Cooperativa"],correct:2,explanation:"A Sociedade Limitada é a mais usada para holdings familiares pela flexibilidade do contrato social e limitação de responsabilidade."},

// -- Novas perguntas --
{category:"Direito Societário",question:"O que é a SPE (Sociedade de Propósito Específico) no mercado imobiliário?",options:["Uma sociedade sem fins lucrativos","Sociedade criada para um empreendimento específico, isolando riscos","Uma cooperativa de moradores","Uma empresa estatal de habitação"],correct:1,explanation:"A SPE é constituída para um empreendimento específico, isolando seu patrimônio e riscos dos demais negócios dos sócios."},
{category:"Direito Societário",question:"O que é o SCP (Sociedade em Conta de Participação) e como é usada no mercado imobiliário?",options:["Sociedade registrada na Junta Comercial para construção","Sociedade não personificada entre um sócio ostensivo e sócios participantes, usada para investimentos imobiliários","Consórcio de construtoras","Cooperativa habitacional"],correct:1,explanation:"A SCP é sociedade sem personalidade jurídica onde o sócio ostensivo opera e os participantes investem, comum em empreendimentos imobiliários (arts. 991 a 996 CC)."},
{category:"Direito Societário",question:"O que é o acordo de sócios (ou quotistas) em uma holding imobiliária?",options:["O contrato social registrado na Junta","Documento que regulamenta direitos, obrigações e restrições entre os sócios além do contrato social","A procuração para o administrador","O plano de negócios da empresa"],correct:1,explanation:"O acordo de sócios é instrumento parassocial que regula temas como distribuição de lucros, governança e restrições à transferência de quotas."},
{category:"Direito Societário",question:"O que é a cláusula de incomunicabilidade das quotas em uma holding familiar?",options:["As quotas não podem ser vendidas","As quotas não se comunicam ao cônjuge do sócio em caso de casamento ou divórcio","As quotas não pagam imposto","As quotas não podem ser penhoradas"],correct:1,explanation:"A incomunicabilidade impede que as quotas se comuniquem ao patrimônio do cônjuge, protegendo o patrimônio familiar em caso de separação."},
{category:"Direito Societário",question:"O que é a affectio societatis?",options:["O endereço da sede social","A vontade e disposição dos sócios de se unirem e permanecerem associados para alcançar um objetivo comum","O capital social mínimo","A responsabilidade dos sócios"],correct:1,explanation:"Affectio societatis é o elemento volitivo que representa a intenção dos sócios em colaborar para o sucesso da sociedade."},
{category:"Direito Societário",question:"Qual é a vantagem de integralizar imóveis no capital social de uma holding patrimonial?",options:["O imóvel fica isento de IPTU para sempre","Pode-se transferir os imóveis com alíquota reduzida de ITBI ou mesmo isenção, dependendo do município","O imóvel dobra de valor automaticamente","Não há nenhuma vantagem"],correct:1,explanation:"A integralização de imóveis ao capital social pode ter isenção ou redução de ITBI em diversos municípios (art. 156, §2º, I, CF), exceto se a atividade preponderante for imobiliária."},
{category:"Direito Societário",question:"Quando a isenção de ITBI na integralização de imóveis ao capital NÃO se aplica?",options:["Quando o imóvel vale mais de R$ 1 milhão","Quando a atividade preponderante da empresa for compra, venda ou locação de imóveis","Quando houver mais de 3 sócios","Quando a holding for Ltda. ao invés de S.A."],correct:1,explanation:"Se a atividade preponderante da empresa for imobiliária (compra, venda, locação), a imunidade de ITBI não se aplica (art. 37, CF e art. 156, §2º, I, CF)."},
{category:"Direito Societário",question:"O que é o pro labore na administração de uma holding imobiliária?",options:["O lucro distribuído aos sócios","A remuneração paga ao sócio-administrador pelo trabalho de gestão","O valor das quotas de cada sócio","A taxa de administração do condomínio"],correct:1,explanation:"Pro labore é a remuneração do sócio-administrador pelo trabalho efetivo de gestão da empresa, sujeito a INSS e IRPF."},
{category:"Direito Societário",question:"O que é o planejamento sucessório por meio de holding familiar?",options:["Venda antecipada dos imóveis","Organização da transferência patrimonial em vida, via doação de quotas com usufruto, evitando inventário","Seguro de vida para os herdeiros","Testamento registrado em cartório"],correct:1,explanation:"A holding familiar permite a doação antecipada de quotas com reserva de usufruto, facilitando a sucessão e evitando o inventário judicial."},
{category:"Direito Societário",question:"O que é a cláusula de usufruto vitalício sobre quotas da holding?",options:["O sócio vende suas quotas e continua usando os imóveis","O doador transfere as quotas mas mantém o direito de receber rendimentos e administrar a sociedade até o falecimento","As quotas são devolvidas após 10 anos","O sócio menor recebe dividendos antecipados"],correct:1,explanation:"O usufruto permite que o doador das quotas mantenha o controle da holding e o direito aos frutos (aluguéis, lucros) durante sua vida."},
{category:"Direito Societário",question:"Qual é a diferença entre distribuição de lucros e pro labore para fins tributários?",options:["Não há diferença tributária","Lucros distribuídos são isentos de IR para o sócio PF; pro labore é tributado como renda (IRPF + INSS)","Pro labore é isento e lucros são tributados","Ambos pagam a mesma alíquota de 15%"],correct:1,explanation:"Lucros distribuídos por PJ são isentos de IRPF na pessoa do sócio. O pro labore é tributado pelo IRPF (tabela progressiva) e INSS."},
{category:"Direito Societário",question:"O que é a dissolução parcial de sociedade e quando ocorre no contexto de holdings?",options:["Encerramento total da empresa","Saída de um sócio com apuração de haveres, sem extinção da sociedade","Fusão com outra empresa","Mudança de endereço da sede"],correct:1,explanation:"A dissolução parcial permite a saída de sócio (ou exclusão) com apuração de seus haveres, mantendo a sociedade em funcionamento (arts. 1.028 a 1.032 CC)."},
{category:"Direito Societário",question:"O que é a SLU (Sociedade Limitada Unipessoal)?",options:["Sociedade com no mínimo 5 sócios","Sociedade limitada formada por apenas um sócio, permitida desde 2019","Sociedade anônima com um acionista","Sociedade estrangeira registrada no Brasil"],correct:1,explanation:"A SLU permite a constituição de sociedade limitada por um único sócio, eliminando a necessidade de sócio 'de fachada' (art. 1.052, §1º, CC, Lei 13.874/2019)."},
{category:"Direito Societário",question:"Na holding patrimonial, o que é o regime tributário do Lucro Presumido?",options:["Tributação sobre o lucro contábil real","Regime simplificado que presume o lucro com base em percentual da receita bruta","Isenção total de impostos para holdings","Regime exclusivo para microempresas"],correct:1,explanation:"No Lucro Presumido, o lucro é presumido com base em percentuais sobre a receita bruta (32% para aluguéis, 8% para venda de imóveis), simplificando a apuração."},
{category:"Direito Societário",question:"Qual é o quórum para alteração do contrato social de uma Sociedade Limitada?",options:["Maioria simples (50%+1)","3/4 do capital social","Unanimidade dos sócios","2/3 do capital social"],correct:1,explanation:"A alteração do contrato social exige aprovação de sócios que representem, no mínimo, 3/4 (75%) do capital social (art. 1.076, I, CC)."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 5: DIREITO TRIBUTÁRIO (35 perguntas)               ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Direito Tributário",question:"Qual imposto incide sobre a transmissão de bens imóveis por ato inter vivos (compra e venda)?",options:["ITCMD","IPTU","ITBI","ISS"],correct:2,explanation:"O ITBI (Imposto de Transmissão de Bens Imóveis) incide sobre transações onerosas de imóveis, de competência municipal (art. 156, II, CF)."},
{category:"Direito Tributário",question:"No Lucro Presumido, qual é a base de presunção para atividades imobiliárias de compra e venda?",options:["32% da receita bruta","8% da receita bruta","12% da receita bruta","16% da receita bruta"],correct:1,explanation:"Para venda de imóveis no Lucro Presumido, a base de presunção do IRPJ é 8% da receita bruta (art. 15, Lei 9.249/95)."},
{category:"Direito Tributário",question:"O ITCMD (Imposto sobre Transmissão Causa Mortis e Doação) é de competência de qual ente federativo?",options:["União","Municípios","Estados e Distrito Federal","Autarquias federais"],correct:2,explanation:"O ITCMD é de competência dos Estados e do Distrito Federal (art. 155, I, CF)."},

// -- Novas perguntas --
{category:"Direito Tributário",question:"Qual é a alíquota máxima do ITCMD segundo a Constituição Federal?",options:["4%","8%","15%","20%"],correct:1,explanation:"O Senado Federal fixou a alíquota máxima do ITCMD em 8% (Resolução 9/92). Cada estado define sua alíquota dentro desse limite."},
{category:"Direito Tributário",question:"O que é o ganho de capital na venda de imóveis por pessoa física e qual a alíquota?",options:["Diferença entre valor de compra e venda, tributada a 15%","O valor total da venda, tributado a 27,5%","Apenas o valor acima de R$ 1 milhão, tributado a 10%","Não há tributação sobre venda de imóveis"],correct:0,explanation:"O ganho de capital (lucro na venda) é tributado a 15% para ganhos até R$ 5 milhões, com alíquotas progressivas acima disso (Lei 8.981/95)."},
{category:"Direito Tributário",question:"Em qual situação a pessoa física é ISENTA de imposto sobre ganho de capital na venda de imóvel residencial?",options:["Quando vende imóvel comercial","Quando utiliza o produto da venda para adquirir outro imóvel residencial em até 180 dias","Quando o imóvel foi adquirido há mais de 5 anos","Quando o valor da venda é inferior a R$ 100 mil"],correct:1,explanation:"Há isenção se o valor da venda de imóvel residencial for integralmente utilizado na compra de outro imóvel residencial em 180 dias (art. 39, Lei 11.196/2005)."},
{category:"Direito Tributário",question:"Imóvel adquirido antes de 1969 por pessoa física possui qual benefício fiscal na venda?",options:["Alíquota reduzida de 5%","Isenção total do imposto sobre ganho de capital","Parcelamento do imposto em 120 meses","Dedução de 50% do valor venal"],correct:1,explanation:"Imóveis adquiridos até 1969 têm redução de 100% do ganho de capital (fator de redução previsto no art. 18, Lei 7.713/88)."},
{category:"Direito Tributário",question:"O que é o IPTU progressivo no tempo previsto no Estatuto da Cidade?",options:["Aumento anual automático do IPTU de todos os imóveis","Alíquota crescente para imóveis urbanos que não cumprem a função social da propriedade","Desconto para aposentados","Isenção para imóveis em áreas de risco"],correct:1,explanation:"O IPTU progressivo no tempo é aplicado a imóveis que não atendem à função social, com alíquotas crescentes por até 5 anos (art. 7º, Estatuto da Cidade)."},
{category:"Direito Tributário",question:"Qual é a base de presunção do IRPJ no Lucro Presumido para receitas de aluguel de imóveis?",options:["8%","12%","32%","16%"],correct:2,explanation:"Para receitas de aluguel e prestação de serviços em geral, a base de presunção do IRPJ é 32% da receita bruta (art. 15, §1º, III, 'a', Lei 9.249/95)."},
{category:"Direito Tributário",question:"Qual é a alíquota do IRPJ sobre o lucro presumido?",options:["10%","15%","20%","25%"],correct:1,explanation:"A alíquota do IRPJ é de 15% sobre o lucro presumido, com adicional de 10% sobre o excedente de R$ 20 mil/mês (art. 3º, Lei 9.249/95)."},
{category:"Direito Tributário",question:"O que é a CSLL e como incide sobre empresas do mercado imobiliário?",options:["Contribuição Social sobre Lucros Líquidos — incide sobre o lucro da empresa","Certidão Social de Licença para Locação","Contribuição Sindical de Livre Licitação","Cadastro Social de Locadores Legais"],correct:0,explanation:"A CSLL incide sobre o lucro das empresas à alíquota de 9%, sendo base presumida de 12% (venda) ou 32% (aluguéis) no Lucro Presumido."},
{category:"Direito Tributário",question:"Quais tributos federais incidem sobre a receita de aluguel recebida por holding imobiliária no Lucro Presumido?",options:["Apenas IRPJ","IRPJ, CSLL, PIS e COFINS","Apenas ISS e IPTU","ICMS e IPI"],correct:1,explanation:"No Lucro Presumido, incidem IRPJ (15%), CSLL (9% sobre base presumida), PIS (0,65%) e COFINS (3%) sobre a receita."},
{category:"Direito Tributário",question:"O PIS e COFINS cumulativos no Lucro Presumido incidem sobre aluguel de imóveis com quais alíquotas?",options:["1,65% e 7,6%","0,65% e 3%","2% e 5%","0% (isentos)"],correct:1,explanation:"No regime cumulativo (Lucro Presumido), PIS é 0,65% e COFINS é 3% sobre a receita bruta (Leis 9.718/98, 10.637/02 e 10.833/03)."},
{category:"Direito Tributário",question:"O que é o ITR e quem é obrigado a pagá-lo?",options:["Imposto sobre Transações Rurais — pago por compradores","Imposto Territorial Rural — pago por proprietários de imóveis rurais","Imposto de Transmissão de Registros — pago por cartórios","Índice de Transferência Registral — usado por avaliadores"],correct:1,explanation:"O ITR é imposto federal sobre a propriedade rural (art. 153, VI, CF), pago anualmente pelo proprietário."},
{category:"Direito Tributário",question:"O que é o RET (Regime Especial de Tributação) para incorporações imobiliárias?",options:["Regime que tributa a 27,5% o lucro das incorporadoras","Regime que unifica IRPJ, CSLL, PIS e COFINS em alíquota única de 4% sobre receitas do empreendimento","Regime de isenção para construtoras de habitação popular","Regime de tributação sobre remessas ao exterior"],correct:1,explanation:"O RET permite tributação unificada de 4% sobre receitas da incorporação (1% para MCMV), mediante patrimônio de afetação (Lei 10.931/2004)."},
{category:"Direito Tributário",question:"O que é o come-cotas nos fundos imobiliários?",options:["Desconto semestral de IR que reduz a quantidade de cotas","Não existe come-cotas em FIIs — os rendimentos distribuídos são isentos de IR para PF","Taxa de administração cobrada em cotas","Imposto sobre compra de novas cotas"],correct:1,explanation:"FIIs não têm come-cotas. Rendimentos distribuídos são isentos de IR para pessoa física (com condições), mas o ganho de capital na venda de cotas é tributado a 20%."},
{category:"Direito Tributário",question:"Qual é a alíquota do imposto de renda sobre ganho de capital na venda de cotas de FII?",options:["15%","20%","10%","27,5%"],correct:1,explanation:"O ganho de capital na alienação de cotas de FII é tributado à alíquota de 20% (art. 2º, Lei 11.033/2004)."},
{category:"Direito Tributário",question:"O que é a isenção do ganho de capital na venda de imóvel de até R$ 440 mil para pessoa física?",options:["Qualquer imóvel até esse valor é isento","Isenção se for o único imóvel do vendedor e ele não tiver vendido outro nos últimos 5 anos","Isenção apenas para imóveis rurais","Não existe essa isenção"],correct:1,explanation:"A venda de imóvel de até R$ 440 mil é isenta se for o único imóvel do contribuinte e não tenha havido outra alienação nos últimos 5 anos (art. 23, Lei 9.250/95)."},
{category:"Direito Tributário",question:"O que é o DIMOB e quem é obrigado a apresentá-lo?",options:["Declaração de Imóveis Mobiliados — para locadores","Declaração de Informações sobre Atividades Imobiliárias — obrigatória para imobiliárias e incorporadoras","Documento de Inscrição Municipal de Obras e Benfeitorias","Demonstrativo de Impostos Municipais sobre Bens"],correct:1,explanation:"O DIMOB é a declaração anual à Receita Federal das operações imobiliárias realizadas por imobiliárias, incorporadoras e administradoras de imóveis (IN RFB 1.115/2010)."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  CATEGORIA 6: REFORMA TRIBUTÁRIA (35 perguntas)               ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Do material do usuário --
{category:"Reforma Tributária",question:"Com a entrada em vigor da CBS, qual poderá ser um dos principais impactos para quem aufere renda com aluguel de imóveis?",options:["O aluguel passará a ser isento de qualquer tributação federal","Dependendo do enquadramento, a receita de aluguel poderá sofrer incidência da CBS","Apenas imóveis comerciais estarão sujeitos à CBS","A CBS substituirá exclusivamente o IPTU"],correct:1,explanation:"A CBS poderá incidir sobre receitas de aluguel dependendo do enquadramento do contribuinte e da forma de exploração do imóvel."},
{category:"Reforma Tributária",question:"O Cadastro Imobiliário Brasileiro (CIB), o 'CPF do imóvel', tem como principal finalidade:",options:["Substituir o registro no Cartório de Registro de Imóveis","Servir como documento obrigatório para compra e venda","Criar identificação única para imóveis, facilitando gestão cadastral pelos órgãos públicos","Determinar automaticamente o valor venal para cobrança de IPTU"],correct:2,explanation:"O CIB cria uma identificação numérica única para cada imóvel, integrando cadastros públicos e facilitando a gestão tributária e fundiária."},

// -- Novas perguntas --
{category:"Reforma Tributária",question:"A Reforma Tributária (EC 132/2023) substitui quais tributos pelo IBS e CBS?",options:["IRPJ e CSLL","ICMS, ISS, PIS, COFINS e IPI","Apenas o IPTU e ITBI","ITCMD e ITR"],correct:1,explanation:"O IBS substitui ICMS e ISS, e a CBS substitui PIS, COFINS e IPI, unificando a tributação sobre o consumo."},
{category:"Reforma Tributária",question:"Qual é o redutor de alíquota aplicável às operações imobiliárias na Reforma Tributária?",options:["20%","40%","50%","60%"],correct:1,explanation:"As operações com bens imóveis terão redução de 40% nas alíquotas de IBS e CBS, conforme a Lei Complementar da Reforma."},
{category:"Reforma Tributária",question:"O que é o 'redutor de ajuste' nas operações imobiliárias da Reforma Tributária?",options:["Desconto no valor do ITBI","Mecanismo que reduz a base de cálculo do IBS/CBS para evitar cumulatividade em imóveis adquiridos antes da reforma","Redução automática do IPTU","Desconto no registro do imóvel"],correct:1,explanation:"O redutor de ajuste deduz da base de cálculo o custo de aquisição do imóvel (quando adquirido antes da reforma e sem crédito), evitando tributação em cascata."},
{category:"Reforma Tributária",question:"O que é o 'redutor social' para operações imobiliárias na Reforma Tributária?",options:["Isenção para imóveis de luxo","Desconto fixo na base de cálculo para imóveis residenciais novos e locação, beneficiando habitação popular","Redução do IPTU para aposentados","Subsídio do governo para construtoras"],correct:1,explanation:"O redutor social é um valor fixo deduzido da base de cálculo das operações imobiliárias, beneficiando especialmente habitação de menor valor."},
{category:"Reforma Tributária",question:"Durante o período de transição da Reforma Tributária, quando a CBS começa a ser cobrada?",options:["2025","2026","2027","2029"],correct:1,explanation:"A CBS começa a ser cobrada em 2026 com alíquota-teste de 0,9%, passando à alíquota integral em 2027."},
{category:"Reforma Tributária",question:"Em qual ano o IBS começa a ser cobrado na transição da Reforma Tributária?",options:["2026","2027","2029","2033"],correct:2,explanation:"O IBS entra em vigor gradualmente a partir de 2029, com elevação progressiva das alíquotas até 2033, quando ICMS e ISS são extintos."},
{category:"Reforma Tributária",question:"O que é o split payment na Reforma Tributária e como afeta transações imobiliárias?",options:["Parcelamento do imposto em 12 vezes","Sistema em que o pagamento do tributo é separado automaticamente no momento da transação financeira","Divisão do ITBI entre comprador e vendedor","Pagamento antecipado de 50% do imposto"],correct:1,explanation:"O split payment separa automaticamente o valor do IBS/CBS no momento do pagamento, repassando-o diretamente ao fisco."},
{category:"Reforma Tributária",question:"A locação de imóveis por pessoa física será tributada pelo IBS/CBS na Reforma Tributária?",options:["Sim, toda locação será tributada","Não, a locação por pessoa física com até 3 imóveis (ou receita dentro do limite) é considerada não-contribuinte","Apenas imóveis acima de R$ 5 mil de aluguel","Somente se o locador tiver CNPJ"],correct:1,explanation:"Pessoa física que aluga até 3 imóveis (ou receita bruta anual dentro do limite legal) não é considerada contribuinte do IBS/CBS sobre aluguéis."},
{category:"Reforma Tributária",question:"Como a Reforma Tributária impacta as holdings patrimoniais que administram imóveis para locação?",options:["Holdings ficam isentas de todos os tributos","Holdings serão contribuintes do IBS/CBS sobre aluguéis, mas com redutor de 40% na alíquota","Holdings serão extintas por lei","Não há nenhum impacto"],correct:1,explanation:"Holdings que locam imóveis serão contribuintes do IBS/CBS, porém com alíquota reduzida em 40% e possibilidade de créditos."},
{category:"Reforma Tributária",question:"O que acontece com o PIS e COFINS sobre aluguéis após a implementação total da Reforma Tributária?",options:["Continuam existindo normalmente","São substituídos pela CBS","São reduzidos pela metade","São incorporados ao IRPJ"],correct:1,explanation:"PIS e COFINS serão completamente substituídos pela CBS a partir da implementação integral da reforma."},
{category:"Reforma Tributária",question:"A Reforma Tributária alterou as regras do ITCMD. Qual é a principal mudança?",options:["O ITCMD foi extinto","O ITCMD passará a ter alíquotas progressivas obrigatoriamente","A alíquota máxima foi reduzida para 2%","O ITCMD passou a ser competência federal"],correct:1,explanation:"A EC 132/2023 determinou que o ITCMD tenha alíquotas progressivas, ou seja, quanto maior o valor da herança/doação, maior a alíquota."},
{category:"Reforma Tributária",question:"Qual é a alíquota de referência estimada do IBS + CBS somados?",options:["15%","20%","26,5%","35%"],correct:2,explanation:"A alíquota de referência estimada é de aproximadamente 26,5% (IBS + CBS somados), mas com redutores específicos para cada setor."},
{category:"Reforma Tributária",question:"Na Reforma Tributária, qual é a alíquota efetiva estimada para operações imobiliárias após o redutor de 40%?",options:["Aproximadamente 26,5%","Aproximadamente 15,9%","Aproximadamente 10%","Aproximadamente 5%"],correct:1,explanation:"Com o redutor de 40% sobre a alíquota de referência (~26,5%), a alíquota efetiva para operações imobiliárias ficaria em torno de 15,9%."},
{category:"Reforma Tributária",question:"A venda de imóvel por pessoa física será tributada pelo IBS/CBS?",options:["Sim, todas as vendas","Não, pessoa física que vende imóvel próprio não é considerada contribuinte habitual","Apenas acima de R$ 500 mil","Somente na segunda venda em 12 meses"],correct:1,explanation:"A venda esporádica de imóvel por pessoa física não caracteriza habitualidade, logo não incide IBS/CBS — incide apenas o ganho de capital (IR)."},
{category:"Reforma Tributária",question:"Como funciona o sistema de créditos do IBS/CBS para incorporadoras?",options:["Não há direito a crédito","A incorporadora pode se creditar do IBS/CBS pago em insumos (materiais, serviços) para abater do tributo devido","O crédito é limitado a 10% do valor da obra","Apenas créditos de ICMS são aproveitáveis"],correct:1,explanation:"O IBS/CBS são não-cumulativos: a incorporadora aproveita créditos dos tributos pagos em insumos, reduzindo o valor a pagar na venda das unidades."},
{category:"Reforma Tributária",question:"O que é o princípio do destino adotado pela Reforma Tributária e como afeta o mercado imobiliário?",options:["O imposto é recolhido no local de produção","O IBS é devido ao município/estado onde o imóvel está localizado (destino da operação)","O imposto vai para o município sede da construtora","O princípio do destino só se aplica a exportações"],correct:1,explanation:"O IBS será cobrado no local do consumo/destino — para imóveis, no município onde o bem está localizado, redistribuindo receitas."},
{category:"Reforma Tributária",question:"A Reforma Tributária prevê tratamento diferenciado para habitação de interesse social?",options:["Não, todas as habitações são tratadas igualmente","Sim, com redutores sociais maiores e possível alíquota zero para programas habitacionais","Apenas isenção de IPTU","Somente financiamento a juros zero"],correct:1,explanation:"A reforma prevê redutores sociais amplificados e possibilidade de alíquota zero para operações do programa Minha Casa Minha Vida e similares."},
{category:"Reforma Tributária",question:"Qual é o papel do Comitê Gestor do IBS na Reforma Tributária?",options:["Fiscalizar obras de construção civil","Administrar a arrecadação e distribuição do IBS entre estados e municípios","Definir o valor venal dos imóveis","Aprovar projetos de incorporação"],correct:1,explanation:"O Comitê Gestor é o órgão intergovernamental responsável por administrar o IBS, definir normas, arrecadar e distribuir os recursos."},
{category:"Reforma Tributária",question:"A Reforma Tributária impacta o Simples Nacional para imobiliárias?",options:["O Simples Nacional foi extinto","Empresas no Simples continuam com regime próprio, mas podem optar por IBS/CBS em operações imobiliárias","Todas as imobiliárias saem do Simples obrigatoriamente","O Simples passa a cobrar alíquota única de 4%"],correct:1,explanation:"O Simples Nacional é mantido, mas contribuintes podem optar pelo regime geral de IBS/CBS quando mais vantajoso em operações imobiliárias."},
{category:"Reforma Tributária",question:"Qual é o impacto da Reforma Tributária nos FIIs (Fundos de Investimento Imobiliário)?",options:["FIIs ficam isentos de todos os tributos","FIIs podem ser contribuintes do IBS/CBS quando auferem receitas de aluguel","FIIs são extintos pela reforma","Apenas FIIs de papel são afetados"],correct:1,explanation:"FIIs que exploram imóveis (aluguel) podem ser contribuintes do IBS/CBS sobre essas receitas, com o redutor de 40%."},
{category:"Reforma Tributária",question:"A Reforma Tributária altera o ITBI municipal?",options:["Sim, o ITBI é extinto e incorporado ao IBS","Não, o ITBI permanece como tributo municipal independente","O ITBI é transferido para a competência estadual","O ITBI passa a ter alíquota nacional única de 2%"],correct:1,explanation:"O ITBI não é afetado diretamente pela reforma — continua como imposto municipal sobre transmissão onerosa de imóveis (art. 156, II, CF)."},
{category:"Reforma Tributária",question:"Na transição da Reforma, quando ICMS e ISS serão completamente extintos?",options:["2027","2029","2033","2035"],correct:2,explanation:"ICMS e ISS serão gradualmente substituídos pelo IBS entre 2029 e 2032, sendo completamente extintos em 2033."},
{category:"Reforma Tributária",question:"O que muda para o corretor de imóveis pessoa física com a Reforma Tributária?",options:["Passa a pagar IBS/CBS sobre todas as comissões","Quem exerce atividade habitual e aufere receita acima do limite pode ser contribuinte do IBS/CBS","Fica isento de todos os tributos","Deve se tornar pessoa jurídica obrigatoriamente"],correct:1,explanation:"Corretores PF que atuam com habitualidade e ultrapassam o limite de receita poderão ser contribuintes do IBS/CBS sobre suas comissões."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  PERGUNTAS BÓZEO ADVOCACIA (Bônus/Institucional)             ║
// ╚═══════════════════════════════════════════════════════════════╝

{category:"Bózeo Advocacia",question:"Dentro da estratégia de gestão da Bózeo Advocacia, o que contempla o '1º Passo' para a Gestão da Segurança?",options:["Análise de todos os contratos, elaboração de padrões e verificação tributária da imobiliária","Realização de workshops semanais com todos os corretores","Ajuizamento imediato de ações de despejo para inadimplentes","Execução de títulos extrajudiciais acima de 40 salários mínimos"],correct:0,explanation:"O 1º Passo do onboarding da Bózeo contempla a análise de contratos, padronização documental e verificação tributária da imobiliária."},
{category:"Bózeo Advocacia",question:"Como funciona o 'Bônus Educacional' oferecido pela Bózeo Advocacia em seus planos?",options:["Desconto em cursos de pós-graduação para sócios","Consultoria jurídica individualizada para cada cliente","Workshop a cada 6 meses com tema de escolha da imobiliária","Treinamento diário sobre novas leis"],correct:2,explanation:"O Bônus Educacional consiste em um workshop semestral com tema escolhido pela imobiliária, promovendo educação continuada."},

// ╔═══════════════════════════════════════════════════════════════╗
// ║  PERGUNTAS ADICIONAIS — completando 200+                     ║
// ╚═══════════════════════════════════════════════════════════════╝

// -- Direito Imobiliário (extras) --
{category:"Direito Imobiliário",question:"O que é a ação de despejo por falta de pagamento?",options:["Ação para cobrar IPTU em atraso","Ação judicial para retomar o imóvel locado quando o inquilino não paga aluguel","Ação para demolir construção irregular","Processo de execução fiscal"],correct:1,explanation:"A ação de despejo por falta de pagamento permite ao locador retomar o imóvel e cobrar aluguéis em atraso (art. 9º, III, Lei 8.245/91)."},
{category:"Direito Imobiliário",question:"O que é o direito de arrependimento na compra de imóvel na planta?",options:["O comprador pode desistir a qualquer momento sem penalidade","O comprador pode desistir em até 7 dias se a compra ocorreu fora do estabelecimento comercial","Não existe direito de arrependimento para imóveis","O vendedor pode cancelar a venda em até 30 dias"],correct:1,explanation:"O direito de arrependimento de 7 dias aplica-se quando a aquisição ocorre fora do estabelecimento comercial (art. 49, CDC), como em feirões."},
{category:"Direito Imobiliário",question:"O que é o Fundo de Investimento Imobiliário (FII)?",options:["Poupança vinculada a imóveis","Comunhão de recursos de investidores aplicados em empreendimentos imobiliários, com cotas negociadas em bolsa","Financiamento coletivo para construção","Consórcio de imóveis"],correct:1,explanation:"O FII é um veículo de investimento coletivo em imóveis ou títulos imobiliários, com cotas negociáveis em bolsa (Lei 8.668/93)."},
{category:"Direito Imobiliário",question:"Qual é o prazo de garantia do construtor para vícios ocultos após a entrega do imóvel?",options:["30 dias","90 dias","5 anos pela garantia legal do CC, podendo chegar a 10 anos por jurisprudência","1 ano"],correct:2,explanation:"O CC prevê garantia de 5 anos pela solidez (art. 618). A jurisprudência permite reclamação em até 10 anos (5 de garantia + 5 de prescrição)."},
{category:"Direito Imobiliário",question:"O que é a convenção de condomínio?",options:["Reunião mensal dos condôminos","Documento que estabelece as regras de uso e administração do condomínio edilício","O contrato de locação do salão de festas","O projeto arquitetônico do prédio"],correct:1,explanation:"A convenção de condomínio é o ato normativo que disciplina direitos e deveres dos condôminos, aprovada por 2/3 das frações ideais (art. 1.333 CC)."},
{category:"Direito Imobiliário",question:"O condômino inadimplente pode ser impedido de usar áreas comuns do condomínio?",options:["Sim, pode ser impedido de usar qualquer área","Não, o uso das áreas comuns é inerente à propriedade e não pode ser restringido como punição por inadimplência","Apenas se a convenção autorizar","Somente após decisão judicial"],correct:1,explanation:"O STJ entende que restringir o uso de áreas comuns como punição ao inadimplente é abusivo, pois o direito de uso decorre da propriedade."},
{category:"Direito Imobiliário",question:"O que é a REURB (Regularização Fundiária Urbana)?",options:["Reforma de imóveis antigos","Conjunto de medidas jurídicas e urbanísticas para regularizar assentamentos informais","Recadastramento de contribuintes do IPTU","Renovação de licenças ambientais"],correct:1,explanation:"A REURB (Lei 13.465/2017) compreende medidas para formalizar a propriedade em áreas ocupadas irregularmente."},
{category:"Direito Imobiliário",question:"O que é o direito de vizinhança no Código Civil?",options:["Obrigação de cumprimentar os vizinhos","Conjunto de normas que regulam os conflitos entre proprietários de imóveis contíguos","Lei municipal sobre barulho","Direito de usar a piscina do vizinho"],correct:1,explanation:"O direito de vizinhança regula uso anormal da propriedade, árvores limítrofes, passagem forçada, entre outros (arts. 1.277 a 1.313 CC)."},

// -- Direito Trabalhista (extras) --
{category:"Direito Trabalhista",question:"O que são as horas in itinere e elas se aplicam ao corretor de imóveis?",options:["Horas extras noturnas","Tempo de deslocamento casa-trabalho que era computado como jornada — suprimido pela Reforma Trabalhista","Intervalo para almoço","Horas de treinamento obrigatório"],correct:1,explanation:"As horas in itinere foram suprimidas pela Reforma Trabalhista (art. 58, §2º, CLT). O tempo de deslocamento não é mais computado na jornada."},
{category:"Direito Trabalhista",question:"O que é o teletrabalho (home office) e como se aplica ao mercado imobiliário?",options:["Trabalho realizado apenas por telefone","Prestação de serviços fora das dependências do empregador, com uso de tecnologia, previsto na CLT","Trabalho em tempo parcial","Estágio remoto"],correct:1,explanation:"O teletrabalho é regulado pelos arts. 75-A a 75-F da CLT, aplicável a funções administrativas de imobiliárias."},
{category:"Direito Trabalhista",question:"O que é a terceirização e como impacta as imobiliárias?",options:["Contratação de estagiários","Contratação de empresa para realizar serviços, permitida para qualquer atividade após a Reforma Trabalhista","Sublocação de imóveis","Contratação de freelancers sem contrato"],correct:1,explanation:"A terceirização é permitida para qualquer atividade (inclusive atividade-fim) após a Lei 13.429/2017 e Reforma Trabalhista."},
{category:"Direito Trabalhista",question:"Qual é o adicional de insalubridade e ele pode ser aplicável a trabalhadores da construção civil?",options:["5% sobre o salário base","10%, 20% ou 40% sobre o salário mínimo, dependendo do grau, aplicável a trabalhadores expostos a agentes nocivos na construção","50% sobre horas extras","Não existe mais após a Reforma"],correct:1,explanation:"O adicional de insalubridade é de 10% (mínimo), 20% (médio) ou 40% (máximo), aplicável a trabalhadores expostos a agentes nocivos (art. 192 CLT)."},
{category:"Direito Trabalhista",question:"O que é o banco de horas e como funciona na imobiliária?",options:["Conta bancária para depósito de salários","Sistema de compensação que permite acumular horas extras para folga posterior","Empréstimo de horas entre funcionários","Registro de horas no CRECI"],correct:1,explanation:"O banco de horas permite compensação de horas extras por folgas, podendo ser acordado individualmente por até 6 meses (art. 59, §5º, CLT)."},
{category:"Direito Trabalhista",question:"O que é a estabilidade provisória da gestante e como se aplica em imobiliárias?",options:["A gestante não pode ser demitida durante a gravidez e até 5 meses após o parto","A gestante pode ser demitida com aviso prévio de 90 dias","A estabilidade só vale para empregadas públicas","Não existe estabilidade para gestantes no setor privado"],correct:0,explanation:"A empregada gestante tem estabilidade desde a confirmação da gravidez até 5 meses após o parto (art. 10, II, 'b', ADCT)."},

// -- Direito Previdenciário (extras) --
{category:"Direito Previdenciário",question:"O que é a pensão por morte do INSS e o dependente do corretor autônomo tem direito?",options:["Apenas empregados CLT geram pensão por morte","Sim, desde que o corretor esteja em dia com as contribuições, seus dependentes têm direito","Somente se o corretor tiver mais de 20 anos de contribuição","Apenas cônjuges têm direito"],correct:1,explanation:"A pensão por morte é devida aos dependentes do segurado que mantinha qualidade de segurado (contribuições em dia) ao falecer (art. 74, Lei 8.213/91)."},
{category:"Direito Previdenciário",question:"O que é o auxílio-acidente e o corretor de imóveis empregado tem direito?",options:["Benefício por qualquer tipo de acidente","Indenização mensal para segurado que, após acidente, tem capacidade reduzida para o trabalho","Seguro de vida obrigatório","Adicional por trabalho noturno"],correct:1,explanation:"O auxílio-acidente é uma indenização paga ao segurado que sofre acidente e fica com sequelas que reduzem sua capacidade laboral (art. 86, Lei 8.213/91)."},
{category:"Direito Previdenciário",question:"O que é a contribuição previdenciária sobre a receita bruta (CPRB) e como afeta a construção civil?",options:["Contribuição de 20% sobre a folha","Substituição da contribuição patronal sobre folha por contribuição sobre receita bruta da empresa","Contribuição do empregado sobre seu salário","Imposto sobre aluguel de equipamentos"],correct:1,explanation:"A CPRB substitui os 20% patronais sobre a folha por 1% a 4,5% sobre a receita bruta, beneficiando setores como a construção civil."},

// -- Direito Societário (extras) --
{category:"Direito Societário",question:"O que é a cláusula de não-competição em um contrato societário de imobiliária?",options:["Proibição de anunciar imóveis online","Cláusula que impede o sócio retirante de atuar no mesmo ramo e região por período determinado","Acordo para não competir em leilões","Restrição de vendas em determinados bairros"],correct:1,explanation:"A cláusula de não-competição restringe o sócio retirante de concorrer no mesmo segmento por prazo e área geográfica definidos."},
{category:"Direito Societário",question:"O que é o conselho de administração em uma incorporadora S.A.?",options:["Grupo de moradores do condomínio","Órgão colegiado que define as diretrizes estratégicas da companhia","Departamento de recursos humanos","Comissão de corretores"],correct:1,explanation:"O conselho de administração é o órgão de deliberação colegiada que fixa a orientação geral dos negócios da S.A. (art. 138, Lei 6.404/76)."},
{category:"Direito Societário",question:"O que é a golden share (ação de classe especial)?",options:["Ação que paga dividendos em ouro","Ação que confere poder de veto em certas deliberações ao seu titular","Ação mais cara do mercado","Ação sem direito a voto"],correct:1,explanation:"A golden share confere ao titular (geralmente o Estado em privatizações) poder de veto em matérias específicas (art. 17, §7º, Lei 6.404/76)."},
{category:"Direito Societário",question:"O que é a joint venture no mercado imobiliário?",options:["Compra conjunta de imóvel por duas famílias","Associação entre empresas para realizar um empreendimento específico, compartilhando riscos e lucros","Fusão definitiva de duas construtoras","Leilão de imóveis em conjunto"],correct:1,explanation:"Joint venture é a associação temporária entre empresas para desenvolver um projeto imobiliário específico, sem criar nova pessoa jurídica."},
{category:"Direito Societário",question:"Qual é a responsabilidade do administrador de uma holding patrimonial perante terceiros?",options:["Responsabilidade ilimitada sempre","Não responde pessoalmente se agir dentro de seus poderes e sem culpa ou dolo","Responde até o limite de 50% do capital social","Responde apenas por dívidas trabalhistas"],correct:1,explanation:"O administrador que age nos limites de seus poderes e sem culpa ou dolo não responde pessoalmente pelas obrigações da sociedade (art. 1.012 CC)."},

// -- Direito Tributário (extras) --
{category:"Direito Tributário",question:"O que é a isenção de IR sobre aluguel recebido por pessoa física até o limite da tabela?",options:["Todo aluguel é isento de IR","O aluguel recebido por PF é tributado pelo IRPF conforme tabela progressiva, sendo isento até o limite de isenção mensal","Aluguel de até R$ 10 mil é isento","Não existe isenção para renda de aluguel"],correct:1,explanation:"A renda de aluguel PF compõe a base de cálculo do IRPF mensal (carnê-leão), sendo isenta até o limite da faixa de isenção da tabela."},
{category:"Direito Tributário",question:"O que é o carnê-leão para locadores pessoa física?",options:["Caderno de controle de aluguéis","Recolhimento mensal obrigatório de IRPF sobre aluguéis recebidos de pessoas físicas","Imposto pago apenas na declaração anual","Taxa municipal sobre locação"],correct:1,explanation:"O carnê-leão é o recolhimento mensal do IRPF que o locador PF deve fazer ao receber aluguel de outras pessoas físicas (art. 106, IN RFB 1.500/2014)."},
{category:"Direito Tributário",question:"Qual é a alíquota do ISS sobre serviços de corretagem imobiliária?",options:["Não incide ISS sobre corretagem","De 2% a 5%, conforme legislação do município","10% fixo","15% sobre o valor da comissão"],correct:1,explanation:"O ISS incide sobre serviços de corretagem imobiliária com alíquota entre 2% e 5%, definida por cada município (LC 116/2003)."},
{category:"Direito Tributário",question:"O que é o ITCMD progressivo e como impacta o planejamento sucessório?",options:["É um imposto federal com alíquota fixa","Imposto estadual com alíquotas crescentes conforme o valor da herança/doação, incentivando o planejamento antecipado","É cobrado apenas sobre imóveis rurais","Não existe progressividade no ITCMD"],correct:1,explanation:"Com a EC 132/2023, o ITCMD passou a ser obrigatoriamente progressivo, tornando o planejamento sucessório (holdings, doações em vida) mais relevante."},
{category:"Direito Tributário",question:"O que é o laudêmio cobrado em terrenos de marinha?",options:["Imposto sobre imóveis à beira-mar","Taxa paga à União pela transferência de domínio útil de imóvel em terreno de marinha","Aluguel de praia pela prefeitura","Imposto sobre embarcações"],correct:1,explanation:"O laudêmio é a taxa de 5% sobre o valor do imóvel paga à União na transferência de domínio útil em terrenos de marinha (Decreto-Lei 9.760/46)."},
{category:"Direito Tributário",question:"O que é a taxa de ocupação cobrada em terrenos de marinha?",options:["O percentual do terreno que pode ser construído","Valor anual pago à União pelo uso de terreno de marinha por ocupante regular","Imposto municipal sobre ocupação do solo","Taxa de condomínio em prédios à beira-mar"],correct:1,explanation:"A taxa de ocupação é cobrada anualmente pela SPU dos ocupantes regulares de terrenos de marinha (2% ou 5% do valor do terreno)."},
{category:"Direito Tributário",question:"O que é o GCap (Programa de Ganhos de Capital) da Receita Federal?",options:["Sistema de gestão de carteiras de investimento","Programa para apurar e calcular o imposto de renda sobre ganho de capital na venda de imóveis","Cadastro geral de propriedades","Sistema de avaliação de imóveis"],correct:1,explanation:"O GCap é o programa da Receita Federal usado para calcular o IR sobre ganho de capital na alienação de bens, incluindo imóveis."},

// -- Reforma Tributária (extras) --
{category:"Reforma Tributária",question:"O cashback (devolução de tributos) da Reforma Tributária beneficia quais famílias no setor imobiliário?",options:["Todas as famílias, independente de renda","Famílias de baixa renda inscritas no CadÚnico, incluindo para serviços de locação e concessionárias","Apenas famílias com renda acima de 10 salários mínimos","Somente compradores de imóvel próprio"],correct:1,explanation:"O cashback devolve parte do IBS/CBS pago por famílias de baixa renda (CadÚnico), incluindo gastos com moradia (aluguel, contas)."},
{category:"Reforma Tributária",question:"Como a Reforma Tributária impacta os contratos de locação vigentes na data da transição?",options:["Todos são automaticamente rescindidos","Os contratos em vigor precisarão ser adaptados para contemplar a incidência do IBS/CBS sobre o aluguel","Nenhum impacto, a reforma não atinge contratos existentes","Apenas contratos acima de R$ 5 mil são afetados"],correct:1,explanation:"Contratos de locação vigentes precisarão prever a nova incidência tributária, podendo impactar o valor final pago pelo locatário."},
{category:"Reforma Tributária",question:"O que é o regime de transição do IBS para o mercado imobiliário entre 2029 e 2033?",options:["Cobrança integral desde 2029","Aumento gradual da alíquota do IBS com redução proporcional do ICMS e ISS até 2033","Isenção total durante a transição","Apenas construtoras pagam durante a transição"],correct:1,explanation:"Entre 2029 e 2032, o IBS sobe gradualmente enquanto ICMS e ISS diminuem proporcionalmente, completando a substituição em 2033."},
{category:"Reforma Tributária",question:"A Reforma Tributária criou o IVA dual. O que isso significa?",options:["Dois impostos sobre o mesmo fato gerador","A existência de dois tributos sobre valor agregado: IBS (subnacional) e CBS (federal), com regras harmonizadas","Tributação em dobro para grandes empresas","Cobrança duplicada que será corrigida em 2030"],correct:1,explanation:"O IVA dual brasileiro consiste no IBS (estadual/municipal) e CBS (federal), com bases, regras e alíquotas harmonizadas, mas gestão separada."},
{category:"Reforma Tributária",question:"Como a nota fiscal eletrônica será impactada pela Reforma Tributária no setor imobiliário?",options:["A nota fiscal será eliminada","Todas as operações imobiliárias passarão a exigir nota fiscal eletrônica com discriminação do IBS/CBS","Apenas vendas acima de R$ 1 milhão precisarão de nota","A nota fiscal será substituída pelo CIB"],correct:1,explanation:"A Reforma prevê integração total via nota fiscal eletrônica, com discriminação dos tributos (IBS/CBS), facilitando o controle e a transparência."},

// -- Últimas perguntas para completar 200+ --
{category:"Direito Imobiliário",question:"O que é a ação reivindicatória?",options:["Ação para cobrar aluguel atrasado","Ação do proprietário para retomar a posse de imóvel detido injustamente por terceiro","Ação para registrar imóvel no cartório","Ação para dividir herança"],correct:1,explanation:"A ação reivindicatória é o meio pelo qual o proprietário reivindica o bem de quem injustamente o possua (art. 1.228 CC)."},
{category:"Direito Imobiliário",question:"O que é a enfiteuse (aforamento)?",options:["Tipo de financiamento imobiliário","Direito real em que o proprietário transfere o domínio útil ao enfiteuta, mantendo o domínio direto","Garantia hipotecária especial","Contrato de administração de imóveis"],correct:1,explanation:"A enfiteuse (proibida para novos casos pelo CC/2002) transfere o domínio útil ao enfiteuta, que paga foro anual ao proprietário direto."},
{category:"Direito Trabalhista",question:"O que é a equiparação salarial e quando se aplica no mercado imobiliário?",options:["Todos recebem o mesmo salário","Empregados que exercem mesma função, com mesma produtividade, no mesmo estabelecimento, devem receber igual salário","Equalização de comissões entre corretores","Salário fixado pelo sindicato"],correct:1,explanation:"A equiparação salarial garante salário igual para trabalho de igual valor, mesma função, mesmo empregador e local (art. 461 CLT)."},
{category:"Direito Trabalhista",question:"O que é o adicional de periculosidade e pode ser aplicável na construção civil?",options:["5% sobre o salário base","30% sobre o salário base para trabalhadores expostos a condições perigosas como eletricidade e explosivos","50% sobre horas extras","Não existe na construção civil"],correct:1,explanation:"O adicional de periculosidade é de 30% sobre o salário base para quem trabalha com inflamáveis, explosivos, energia elétrica, etc. (art. 193 CLT)."},
{category:"Direito Previdenciário",question:"O que é o salário-maternidade e a corretora autônoma tem direito?",options:["Apenas empregadas CLT têm direito","Sim, a contribuinte individual tem direito ao salário-maternidade pago pelo INSS","Somente com seguro privado","Apenas para a primeira gravidez"],correct:1,explanation:"A contribuinte individual tem direito ao salário-maternidade pago diretamente pelo INSS, no valor de 1/12 da soma dos últimos 12 salários de contribuição."},
{category:"Direito Previdenciário",question:"O que é a aposentadoria por incapacidade permanente (antiga invalidez)?",options:["Aposentadoria aos 60 anos","Benefício concedido quando o segurado é considerado incapaz total e permanentemente para qualquer trabalho","Aposentadoria especial para corretores","Licença médica de 6 meses"],correct:1,explanation:"A aposentadoria por incapacidade permanente é concedida ao segurado considerado incapaz de forma total e definitiva (art. 42, Lei 8.213/91)."},
{category:"Direito Societário",question:"O que é a cláusula de drag along em um contrato societário?",options:["Direito de arrastar os minoritários na venda — se o majoritário vender, os demais são obrigados a vender nas mesmas condições","Direito de vetar qualquer venda de quotas","Direito de adquirir quotas com desconto","Obrigação de manter as quotas por 10 anos"],correct:0,explanation:"O drag along obriga os sócios minoritários a vender suas quotas junto com o majoritário, nas mesmas condições, facilitando a venda total da empresa."},
{category:"Direito Societário",question:"O que é a cláusula de tag along?",options:["Direito do majoritário de comprar quotas dos minoritários","Direito dos sócios minoritários de vender suas quotas nas mesmas condições oferecidas ao majoritário","Obrigação de manter as quotas por 5 anos","Direito de preferência em aumento de capital"],correct:1,explanation:"O tag along protege os minoritários, garantindo que possam vender suas quotas nas mesmas condições da oferta feita ao sócio majoritário."},
{category:"Direito Tributário",question:"O que é o IPTU verde ou IPTU ecológico?",options:["Imposto sobre imóveis em áreas verdes","Desconto no IPTU concedido por municípios a imóveis que adotam práticas sustentáveis","Imposto sobre resíduos de construção","Taxa ambiental para construtoras"],correct:1,explanation:"O IPTU verde oferece desconto no imposto para imóveis com medidas sustentáveis como energia solar, captação de água da chuva, etc."},
{category:"Direito Tributário",question:"O que é a depreciação de imóveis para fins tributários em holdings?",options:["Desvalorização do imóvel por uso, que gera despesa dedutível reduzindo a base de cálculo do IR","Aumento do valor do imóvel ao longo do tempo","Imposto cobrado sobre imóveis abandonados","Multa por falta de manutenção"],correct:0,explanation:"A depreciação é a perda de valor do imóvel por uso/desgaste, contabilizada como despesa que reduz a base de cálculo dos tributos sobre o lucro (taxa de 4% a.a. para imóveis)."},
{category:"Reforma Tributária",question:"O que é a trava de alíquota prevista na Reforma Tributária?",options:["Limite máximo de 5% para qualquer tributo","Mecanismo que impede a alíquota de referência do IBS/CBS de ultrapassar 26,5%","Congelamento de todos os impostos por 10 anos","Proibição de aumento de IPTU"],correct:1,explanation:"A trava de alíquota é um mecanismo de controle que limita a carga tributária total do IBS+CBS, exigindo revisão de benefícios se ultrapassar o teto."},
{category:"Reforma Tributária",question:"A Reforma Tributária impacta o ganho de capital na venda de imóveis?",options:["Sim, o ganho de capital será substituído pelo IBS","Não, o ganho de capital (IR) continua sendo cobrado separadamente — a reforma trata de tributos sobre o consumo","A reforma isenta todo ganho de capital imobiliário","O ganho de capital passa a ser estadual"],correct:1,explanation:"A reforma trata de tributos sobre consumo (IBS/CBS). O IR sobre ganho de capital permanece inalterado como tributo sobre a renda."},
{category:"Direito Imobiliário",question:"O que é a cédula de crédito imobiliário (CCI)?",options:["Cartão de crédito para compra de imóveis","Título representativo de crédito imobiliário, emitido por credor para negociação no mercado","Certidão do cartório de imóveis","Comprovante de pagamento de parcela"],correct:1,explanation:"A CCI representa créditos imobiliários e pode ser negociada no mercado de capitais, facilitando a securitização (Lei 10.931/2004)."},
{category:"Direito Imobiliário",question:"O que é a LCI (Letra de Crédito Imobiliário)?",options:["Licença para construção de imóveis","Título de renda fixa emitido por bancos, lastreado em créditos imobiliários, isento de IR para PF","Certidão de legalidade do imóvel","Contrato de locação indexado"],correct:1,explanation:"A LCI é um título emitido por instituições financeiras, lastreado em financiamentos imobiliários, com isenção de IR para pessoa física (Lei 10.931/2004)."},
{category:"Direito Imobiliário",question:"O que é a tabela Price e como funciona no financiamento imobiliário?",options:["Tabela de preços de imóveis por região","Sistema de amortização com parcelas fixas, onde no início a maior parte é juros e no final é amortização","Lista de taxas cartorárias","Índice de valorização imobiliária"],correct:1,explanation:"Na tabela Price, as parcelas são constantes. No início, a composição é mais juros e menos amortização, invertendo-se ao longo do tempo."},

];

// ═══════════════════════════════════════════════════════════════
//  UTILITÁRIOS
// ═══════════════════════════════════════════════════════════════

/**
 * Sorteia N perguntas do banco, garantindo variedade de categorias.
 * @param {number} n - Número de perguntas desejadas (padrão: 20)
 * @param {string[]} categories - Categorias para incluir (vazio = todas)
 * @returns {Array} Perguntas sorteadas e embaralhadas
 */
function pickQuestions(n = 20, categories = []) {
  let pool = [...ALL_QUESTIONS];

  // Filtrar por categorias, se especificadas
  if (categories.length > 0) {
    pool = pool.filter(q => categories.includes(q.category));
  }

  // Agrupar por categoria
  const byCategory = {};
  pool.forEach(q => {
    if (!byCategory[q.category]) byCategory[q.category] = [];
    byCategory[q.category].push(q);
  });

  // Embaralhar cada categoria
  Object.values(byCategory).forEach(arr => shuffleArray(arr));

  // Distribuir proporcionalmente
  const catNames = Object.keys(byCategory);
  const perCat = Math.floor(n / catNames.length);
  const remainder = n % catNames.length;

  let selected = [];
  catNames.forEach((cat, i) => {
    const take = perCat + (i < remainder ? 1 : 0);
    selected.push(...byCategory[cat].slice(0, take));
  });

  // Se não alcançou N (categorias com poucas perguntas), completar
  if (selected.length < n) {
    const selectedSet = new Set(selected);
    const remaining = pool.filter(q => !selectedSet.has(q));
    shuffleArray(remaining);
    selected.push(...remaining.slice(0, n - selected.length));
  }

  // Embaralhar resultado final
  shuffleArray(selected);
  return selected.slice(0, n);
}

function shuffleArray(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Estatísticas do banco
function getStats() {
  const stats = {};
  ALL_QUESTIONS.forEach(q => {
    stats[q.category] = (stats[q.category] || 0) + 1;
  });
  return stats;
}
